// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhbK5tY1IWhSAINmvL9FwxsNWmqztMpU',
    appId: '1:258088199360:web:cba967047bb7c6aa423925',
    messagingSenderId: '258088199360',
    projectId: 'simplechatapp-b0834',
    authDomain: 'simplechatapp-b0834.firebaseapp.com',
    storageBucket: 'simplechatapp-b0834.firebasestorage.app',
    measurementId: 'G-QVV471P2GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kgQ0FfW75q2zla9TjHbALoq0YN1r3ro',
    appId: '1:258088199360:android:089f3e31e1ad2dd0423925',
    messagingSenderId: '258088199360',
    projectId: 'simplechatapp-b0834',
    storageBucket: 'simplechatapp-b0834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMl3Yo29eK0MDRYbHHA2bC3phlUjTDOk',
    appId: '1:258088199360:ios:e9b9ee43523e7cc7423925',
    messagingSenderId: '258088199360',
    projectId: 'simplechatapp-b0834',
    storageBucket: 'simplechatapp-b0834.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMl3Yo29eK0MDRYbHHA2bC3phlUjTDOk',
    appId: '1:258088199360:ios:e9b9ee43523e7cc7423925',
    messagingSenderId: '258088199360',
    projectId: 'simplechatapp-b0834',
    storageBucket: 'simplechatapp-b0834.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYhbK5tY1IWhSAINmvL9FwxsNWmqztMpU',
    appId: '1:258088199360:web:7a7cb4cf3cb31a30423925',
    messagingSenderId: '258088199360',
    projectId: 'simplechatapp-b0834',
    authDomain: 'simplechatapp-b0834.firebaseapp.com',
    storageBucket: 'simplechatapp-b0834.firebasestorage.app',
    measurementId: 'G-SLVCZJHMB0',
  );
}
